/*
 * This Code is edited by sun wukong @ 2015.12.07 11:41:48 CST 
 * 
 * Just feel free to use this code as you wish.
 * Any bug and ugly code, please notify me, thanks!
 *
 * Github https://githuc.com/maybe2009
 * Gmail  qtdssunwukong@gmail.com
 * 									-Auto Generated By UltiSnips
 */


#ifndef __IPV4HANDLES_INCLUDED__
#define __IPV4HANDLES_INCLUDED__
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include "ipv4_frame.h"

void    display_raw(const u_char *packet, int packet_size);
void    ip_handle(const struct frame_ip *ip_frame);
void    arp_handle(const struct frame_arp *arp_frame);
void    tcp_handle(const struct frame_tcp *tcp_frame);
void    udp_handle(const struct frame_udp *udp_frame);
char   *gethostbyip(const void *addr, int size, int family);

#endif
