/*
 * This Code is edited by sun wukong @ 2015.12.05 17:54:09 CST 
 * 
 * Just feel free to use this code as you wish.
 * Any bug and ugly code, please notify me, thanks!
 *
 * Github https://githuc.com/maybe2009
 * Gmail  qtdssunwukong@gmail.com
 * 									-Auto Generated By UltiSnips
 */

/* 
 * This module contains callback functions may be used in pcap_loop. 
 * Pick one from them as you wish.
 *
 */

#include "../headers/callback_functions.h"

void got_packet(u_char *args, const struct pcap_pkthdr *header,
                const u_char *packet)
{
    printf("%lu  %lu\n", header->ts.tv_sec, header->ts.tv_usec);
    u_short             eth_type;
    const u_char       *eth_payload;

    const struct frame_ethernet *ethernet_t;
     
    ethernet_t  = (struct frame_ethernet *)packet;
    eth_payload = (packet + ETHERNET_HEADER_SIZE);
    eth_type    = ntohs(ethernet_t->type);

    printf("***********************************************************************\n");   
    
    printf("Pcap header information: length of portion = %d \
            length of packet %d\n", header->caplen, header->len); 
    printf("Ethernet type : %hX\n", eth_type); 
    
    switch(eth_type)
    {
        case VERSION_IS_IPv4 : {
            ip_handle((struct frame_ip *)eth_payload);
            break;
        }
        
        case VERSION_IS_ARP : {
            arp_handle((struct frame_arp *)eth_payload);
            break;       
        }

        default : {
            printf("Unsupport Eternet Version Code.\n");
            break;
        } 
    }
    
    display_raw(packet, header->caplen);
    
    printf("***********************************************************************\n");   
    printf("Handle over\n");

    return;
}

